name: CI/CD Azure Pipeline

on:
  push:
    branches: [ "main", "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del Código
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Apply (Desplegar ACR y Web App)
        run: |
          cd terraform
          terraform apply -auto-approve

      - name: Build y Push de la Imagen Docker a ACR
        run: |
          ACR_SERVER=$(cd terraform && terraform output -raw acr_login_server)
          az acr login --name $ACR_SERVER
          docker build -t $ACR_SERVER/devops-api:latest ./app
          docker push $ACR_SERVER/devops-api:latest

      - name: Reiniciar Web App para cargar la nueva imagen
        run: |
          az webapp restart --name app-devops-lab-2026 --resource-group rg-devops-lab